# Generated by Django 3.0.3 on 2020-02-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_appointmenttime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='art_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_clientfirstname', models.CharField(max_length=50)),
                ('art_clientlastname', models.CharField(max_length=50)),
                ('art_clientdob', models.DateField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastupdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='clientmood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientmoodtitle', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='paintcolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paintcolortitle', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='art_painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_paintingtitle', models.CharField(default='(Untitled)', max_length=200)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastupdated', models.DateTimeField(auto_now=True)),
                ('art_appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackart.art_appointment')),
                ('clientmoods', models.ManyToManyField(to='trackart.clientmood')),
                ('paintcolors', models.ManyToManyField(to='trackart.paintcolor')),
            ],
        ),
        migrations.AddField(
            model_name='art_appointment',
            name='art_clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackart.art_client'),
        ),
    ]
