# Generated by Django 2.1.4 on 2020-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackart', '0002_auto_20200212_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_painting',
            name='art_paintingtitle',
            field=models.CharField(default='(Untitled)', max_length=200),
        ),
        migrations.AddField(
            model_name='art_painting',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
