# Generated by Django 2.1.4 on 2020-02-24 16:16

from django.db import migrations


def forwards_func(apps, schema_editor):
   # We get the model from the versioned app registry;
   # if we directly import it, it'll be the wrong version
   paintcolor = apps.get_model("trackart", "paintcolor")
   db_alias = schema_editor.connection.alias
   paintcolor.objects.using(db_alias).bulk_create([
      paintcolor(paintcolortitle="Red"),
      paintcolor(paintcolortitle="Yellow"),
      paintcolor(paintcolortitle="Blue"),
      paintcolor(paintcolortitle="Orange"),
      paintcolor(paintcolortitle="Green"),
      paintcolor(paintcolortitle="Purple"),
      paintcolor(paintcolortitle="Gray"),
      paintcolor(paintcolortitle="Black"),
      paintcolor(paintcolortitle="White"),
   ])

def reverse_func(apps, schema_editor):
   # forwards_func() creates two Country instances,
   # so reverse_func() should delete them.
   paintcolor = apps.get_model("trackart", "paintcolor")
   db_alias = schema_editor.connection.alias
   paintcolor.objects.using(db_alias).filter(painttitlecolor__in=["Red", "Yellow", "Blue", "Orange", "Green", "Purple", "Gray", "Black", "White"]).delete()

class Migration(migrations.Migration):

   dependencies = [
      ('trackart', '0003_auto_20200213_1034'),
   ]

   operations = [
      migrations.RunPython(forwards_func, reverse_func),
   ]
